In file ${si.filename}, function ${si.func} at line ${si.line}, the order of catch handler is not properly arranged. 